name: build-test-mudcalendar

on
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]

    steps:
      - name: Checkout MudCalendar repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ./Heron.MudCalendar

      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ./Heron.MudCalendar.UnitTests

      - name: Test
        run: dotnet test -c Release --no-build --no-restore --blame-hang --blame-hang-timeout 60s /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverageAttribute' /p:Include='[Heron.MudCalendar]*' /p:CoverletOutput='./TestResults/' --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
        working-directory: ./Heron.MudCalendar.UnitTests

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: ./Heron.MudCalendar.UnitTests/TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}
